insert into employee values (101,'Manager', 'Piotr','Janus' );
insert into employee values (102,'Manager', 'Andrew','Golota' );
insert into employee values (201,'Project Leader', 'Randy' ,'Randsom');
insert into employee values (202,'Project Leader', 'Ivanka' ,'Trump');
insert into employee values (301,'Support', 'Borris' ,'Johnson');
insert into employee values (302,'Support', 'Angela' ,'Merkel');
INSERT INTO PROCESS ( PROCID , PROC_NAME ) VALUES (101, 'Product Complaint');
INSERT INTO PROCESS ( PROCID , PROC_NAME ) VALUES (102, 'Adverse Event');
INSERT INTO PROCESS ( PROCID , PROC_NAME ) VALUES (103, 'Medical Query');
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (101, 'Phone Conversation', 101);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (102, 'Creating Request', 101);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (103, 'Documenting Complaint', 101);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (104, 'Filling up AE/PC Form', 101);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (201, 'Phone Conversation', 102);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (202, 'Creating Request', 102);  
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (203, 'Documenting Details of AE', 102);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (204, 'Filling up AE/PC Form', 102);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (301, 'Phone Conversation', 103);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (302, 'Creating Request', 103);
INSERT INTO TASK( TASKID, TASK_NAME , PROC_ID ) VALUES (303, 'Document Search', 103);